spack:
  definitions:
  - pkgs:
    - gcc@7.3.0
    - cmake
    - openmpi
    - intel-oneapi-mpi
    - fftw+mpi
    - heffte+fftw+cuda cuda_arch=70
    - accfft
    - ffte+mpi
    - swfft
    - 2decomp

  concretizer:
    unify: true
  view: true
  specs:
  - matrix:
    - [$pkgs]
    - ['%gcc@7.3.0']
