name: CI

on:
  push:
    branches: [ 'master', 'gragghia*' ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        library: [heffte, fftw, accfft, ffte, swfft, 2decomp]
        mpi: [openmpi, intel-oneapi-mpi]
      fail-fast: false
    runs-on: gpu_nvidia
    steps:
      - uses: actions/checkout@v3
      - name: Build with ${{ matrix.library }} ${{matrix.mpi}}
        run: .github/workflows/build.sh ${{matrix.mpi}} ${{matrix.library}}
