name: CI

on:
  push:
    branches: [ 'master', 'gragghia*' ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mpi: [openmpi, intel-oneapi-mpi, mpich, mvapich]
        library: [heffte, fftw, accfft, ffte, swfft]
# Removed swfft and 2decomp until they work correctly
      fail-fast: false
    runs-on: gpu_nvidia
    steps:
      - uses: actions/checkout@v3
      - name: Build with spack - ${{ matrix.library }} ${{matrix.mpi}}
        run: .github/workflows/build_spack.sh ${{matrix.mpi}} ${{matrix.library}} gcc@7.3.0
      #- name: Build with cmake - ${{ matrix.library }} ${{matrix.mpi}}
      #  run: .github/workflows/build.sh ${{matrix.mpi}} ${{matrix.library}} gcc@7.3.0
      #- uses: actions/upload-artifact@v3
      #  if: failure()
      #  with:
      #    name: CMakeError.log ${{matrix.mpi}} ${{matrix.library}}
      #    path: build/CMakeFiles/CMakeError.log

